# vi: set ft=ruby

require 'rbconfig'

ROLE_NAME = 'samba'
HOST_NAME = 'test' + ROLE_NAME
VAGRANTFILE_API_VERSION = '2'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'centos70-nocm'
  config.vm.define HOST_NAME do |node|
    node.vm.provision 'ansible' do |ansible|
      ansible.playbook = 'test-full.yml'
    end
  end
end

